/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/evidence-documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence Documents */
        get: operations["list_evidence_documents_v1_evidence_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence Document */
        get: operations["get_evidence_document_v1_evidence_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-documents/{document_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence Document Events */
        get: operations["list_evidence_document_events_v1_evidence_documents__document_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-documents/{document_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprocess Evidence Document */
        post: operations["reprocess_evidence_document_v1_evidence_documents__document_id__reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-documents/{document_id}/retention-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Document Retention */
        post: operations["request_document_retention_v1_evidence_documents__document_id__retention_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-documents/{document_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence Document Versions */
        get: operations["list_evidence_document_versions_v1_evidence_documents__document_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-documents/{document_id}/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence Document Version */
        get: operations["get_evidence_document_version_v1_evidence_documents__document_id__versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingestion-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingestion Job */
        get: operations["get_ingestion_job_v1_ingestion_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/searches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Research Searches */
        get: operations["list_research_searches_v1_research_searches_get"];
        put?: never;
        /** Create Research Search */
        post: operations["create_research_search_v1_research_searches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/searches/{search_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Research Search */
        get: operations["get_research_search_v1_research_searches__search_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/searches/{search_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Research Search */
        post: operations["cancel_research_search_v1_research_searches__search_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/searches/{search_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Research Search Events */
        get: operations["list_research_search_events_v1_research_searches__search_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/uploads/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize Upload */
        post: operations["finalize_upload_v1_uploads_finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/uploads/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Presigned Upload */
        post: operations["create_presigned_upload_v1_uploads_presign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateResearchSearchRequest */
        CreateResearchSearchRequest: {
            /** Comparator */
            comparator?: string | null;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /** Evidence Types */
            evidence_types?: components["schemas"]["StudyDesign"][];
            /**
             * Intended Use
             * @default literature_search
             */
            intended_use: string;
            /** Intervention */
            intervention?: string | null;
            /**
             * Only Approved Sources
             * @default true
             */
            only_approved_sources: boolean;
            /** Population */
            population?: string | null;
            /** Question */
            question: string;
            /** Source Ids */
            source_ids: string[];
        };
        /** DocumentChunkItem */
        DocumentChunkItem: {
            /** Citation Id */
            citation_id: string;
            /** Ordinal */
            ordinal: number;
            /** Page From */
            page_from: number | null;
            /** Page To */
            page_to: number | null;
            /** Section */
            section: string | null;
            /** Text */
            text: string;
            /** Token Count */
            token_count: number;
        };
        /** DocumentDetailResponse */
        DocumentDetailResponse: {
            /** Block Summary */
            block_summary?: {
                [key: string]: string;
            } | null;
            /** Created At */
            created_at: string;
            current_version: components["schemas"]["DocumentVersionSummary"] | null;
            /** Current Version Id */
            current_version_id: string | null;
            /** Document Id */
            document_id: string;
            /** External Id */
            external_id: string | null;
            /** Source Id */
            source_id: string;
            /** Status */
            status: string;
            /** Title */
            title: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** DocumentEventItem */
        DocumentEventItem: {
            /** Code */
            code: string | null;
            /** Created At */
            created_at: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Safe Message */
            safe_message: string | null;
            /** Sequence */
            sequence: number;
            /** Status */
            status: string;
        };
        /** DocumentEventListResponse */
        DocumentEventListResponse: {
            /** Items */
            items: components["schemas"]["DocumentEventItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** DocumentListResponse */
        DocumentListResponse: {
            /** Items */
            items: components["schemas"]["DocumentSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** DocumentSummary */
        DocumentSummary: {
            /** Created At */
            created_at: string;
            /** Document Id */
            document_id: string;
            /** External Id */
            external_id: string | null;
            /** Media Type */
            media_type: string | null;
            /** Source Id */
            source_id: string;
            /** Status */
            status: string;
            /** Title */
            title: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** DocumentVersionDetail */
        DocumentVersionDetail: {
            /** Chunks */
            chunks?: components["schemas"]["DocumentChunkItem"][];
            /** Created At */
            created_at: string;
            /** Filename */
            filename: string | null;
            /** Malware Status */
            malware_status: string | null;
            /** Media Type */
            media_type: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Page Count */
            page_count: number | null;
            /** Parser Name */
            parser_name: string | null;
            /** Parser Version */
            parser_version: string | null;
            /** Phi Status */
            phi_status: string | null;
            /** Sha256 */
            sha256: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Version */
            version: number;
            /** Version Id */
            version_id: string;
        };
        /** DocumentVersionListResponse */
        DocumentVersionListResponse: {
            /** Items */
            items: components["schemas"]["DocumentVersionSummary"][];
        };
        /** DocumentVersionSummary */
        DocumentVersionSummary: {
            /** Created At */
            created_at: string;
            /** Filename */
            filename: string | null;
            /** Malware Status */
            malware_status: string | null;
            /** Media Type */
            media_type: string | null;
            /** Page Count */
            page_count: number | null;
            /** Parser Name */
            parser_name: string | null;
            /** Parser Version */
            parser_version: string | null;
            /** Phi Status */
            phi_status: string | null;
            /** Sha256 */
            sha256: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Version */
            version: number;
            /** Version Id */
            version_id: string;
        };
        /** FinalizeUploadRequest */
        FinalizeUploadRequest: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
        };
        /** FinalizeUploadResponse */
        FinalizeUploadResponse: {
            /** Document Id */
            document_id: string;
            /** Idempotent */
            idempotent: boolean;
            /** Status */
            status: string;
            /** Version Id */
            version_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestionJobDetailResponse */
        IngestionJobDetailResponse: {
            /** Attempt */
            attempt: number;
            /** Created At */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Events */
            events: components["schemas"]["IngestionJobEventItem"][];
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Updated At */
            updated_at: string;
        };
        /** IngestionJobEventItem */
        IngestionJobEventItem: {
            /** Code */
            code: string | null;
            /** Created At */
            created_at: string;
            /** Safe Message */
            safe_message: string | null;
            /** Sequence */
            sequence: number;
            /** Status */
            status: string;
        };
        /** PresignUploadRequest */
        PresignUploadRequest: {
            /** Contains Phi */
            contains_phi: boolean;
            /** External Id */
            external_id?: string | null;
            /** Filename */
            filename: string;
            /** Media Type */
            media_type: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Source Id */
            source_id: string;
        };
        /** PresignUploadResponse */
        PresignUploadResponse: {
            /** Document Id */
            document_id: string;
            /** Expires At */
            expires_at: string;
            /** Job Id */
            job_id: string;
            /** Object Key */
            object_key: string;
            /** Upload Fields */
            upload_fields: {
                [key: string]: string;
            };
            /** Upload Url */
            upload_url: string;
            /** Version Id */
            version_id: string;
        };
        /** ReprocessDocumentRequest */
        ReprocessDocumentRequest: {
            /** Target Chunker Version */
            target_chunker_version: string;
            /** Target Parser Version */
            target_parser_version: string;
            /** Version Id */
            version_id?: string | null;
        };
        /** ReprocessDocumentResponse */
        ReprocessDocumentResponse: {
            /** Document Id */
            document_id: string;
            /** Idempotent */
            idempotent: boolean;
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Version Id */
            version_id: string;
        };
        /** ResearchCancelResponse */
        ResearchCancelResponse: {
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Search Id */
            search_id: string;
            /** Status */
            status: string;
        };
        /** ResearchEventItem */
        ResearchEventItem: {
            /** Created At */
            created_at: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Event Type */
            event_type: string;
            /** Safe Message */
            safe_message: string;
            /** Sequence */
            sequence: number;
        };
        /** ResearchEventListResponse */
        ResearchEventListResponse: {
            /** Items */
            items: components["schemas"]["ResearchEventItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ResearchSearchCreatedResponse */
        ResearchSearchCreatedResponse: {
            /** Job Id */
            job_id: string;
            links: components["schemas"]["ResearchSearchLinks"];
            /** Search Id */
            search_id: string;
            /** Status */
            status: string;
        };
        /** ResearchSearchDetail */
        ResearchSearchDetail: {
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Completed At */
            completed_at?: string | null;
            /** Created At */
            created_at: string;
            /** Current Step */
            current_step?: string | null;
            /** Intended Use */
            intended_use: string;
            /** Job Id */
            job_id?: string | null;
            links: components["schemas"]["ResearchSearchLinks"];
            /** Policy Version */
            policy_version: string;
            /** Question */
            question: string;
            /** Requested Sources */
            requested_sources: string[];
            /** Search Id */
            search_id: string;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
        };
        /** ResearchSearchLinks */
        ResearchSearchLinks: {
            /** Events */
            events: string;
            /** Job */
            job: string;
            /** Self */
            self: string;
        };
        /** ResearchSearchListResponse */
        ResearchSearchListResponse: {
            /** Items */
            items: components["schemas"]["ResearchSearchSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ResearchSearchSummary */
        ResearchSearchSummary: {
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Created At */
            created_at: string;
            /** Job Id */
            job_id?: string | null;
            /** Question */
            question: string;
            /** Search Id */
            search_id: string;
            /** Status */
            status: string;
        };
        /** RetentionRequest */
        RetentionRequest: {
            /** Reason */
            reason: string;
        };
        /** RetentionRequestResponse */
        RetentionRequestResponse: {
            /** Document Id */
            document_id: string;
            /** Status */
            status: string;
        };
        /**
         * StudyDesign
         * @enum {string}
         */
        StudyDesign: "randomized_controlled_trial" | "systematic_review" | "meta_analysis" | "cohort_study" | "case_control_study" | "case_series" | "case_report" | "guideline" | "preprint" | "unknown";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_evidence_documents_v1_evidence_documents_get: {
        parameters: {
            query?: {
                source_id?: string | null;
                status?: string | null;
                media_type?: string | null;
                created_after?: string | null;
                created_before?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_document_v1_evidence_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_document_events_v1_evidence_documents__document_id__events_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentEventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_evidence_document_v1_evidence_documents__document_id__reprocess_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReprocessDocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReprocessDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_document_retention_v1_evidence_documents__document_id__retention_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetentionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetentionRequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_document_versions_v1_evidence_documents__document_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_document_version_v1_evidence_documents__document_id__versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_ingestion_job_v1_ingestion_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_research_searches_v1_research_searches_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchSearchListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_research_search_v1_research_searches_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResearchSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchSearchCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_research_search_v1_research_searches__search_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchSearchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_research_search_v1_research_searches__search_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchCancelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_research_search_events_v1_research_searches__search_id__events_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                search_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchEventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_upload_v1_uploads_finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinalizeUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalizeUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_presigned_upload_v1_uploads_presign_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | null;
                    };
                };
            };
        };
    };
}
