/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/admin/model-gateway/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Provider Health */
        get: operations["list_provider_health_v1_admin_model_gateway_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/model-gateway/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model Gateway Overview */
        get: operations["get_model_gateway_overview_v1_admin_model_gateway_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/model-gateway/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Model Policies */
        get: operations["list_model_policies_v1_admin_model_gateway_policies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/model-gateway/policies/{policy_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Model Policy */
        post: operations["activate_model_policy_v1_admin_model_gateway_policies__policy_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/model-gateway/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Prompt Templates */
        get: operations["list_prompt_templates_v1_admin_model_gateway_prompts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/model-gateway/prompts/{template_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Prompt Template */
        post: operations["activate_prompt_template_v1_admin_model_gateway_prompts__template_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/retrieval/indexes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Retrieval Indexes */
        get: operations["list_retrieval_indexes_v1_admin_retrieval_indexes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/retrieval/indexes/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Retrieval Index */
        post: operations["build_retrieval_index_v1_admin_retrieval_indexes_build_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence Documents */
        get: operations["list_evidence_documents_v1_evidence_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence Document */
        get: operations["get_evidence_document_v1_evidence_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-documents/{document_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence Document Events */
        get: operations["list_evidence_document_events_v1_evidence_documents__document_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-documents/{document_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprocess Evidence Document */
        post: operations["reprocess_evidence_document_v1_evidence_documents__document_id__reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-documents/{document_id}/retention-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Document Retention */
        post: operations["request_document_retention_v1_evidence_documents__document_id__retention_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-documents/{document_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence Document Versions */
        get: operations["list_evidence_document_versions_v1_evidence_documents__document_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-documents/{document_id}/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence Document Version */
        get: operations["get_evidence_document_version_v1_evidence_documents__document_id__versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingestion-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingestion Job */
        get: operations["get_ingestion_job_v1_ingestion_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/searches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Research Searches */
        get: operations["list_research_searches_v1_research_searches_get"];
        put?: never;
        /** Create Research Search */
        post: operations["create_research_search_v1_research_searches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/searches/{search_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Research Search */
        get: operations["get_research_search_v1_research_searches__search_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/searches/{search_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Research Search Answer */
        get: operations["get_research_search_answer_v1_research_searches__search_id__answer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/searches/{search_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Research Search */
        post: operations["cancel_research_search_v1_research_searches__search_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/searches/{search_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Research Search Events */
        get: operations["list_research_search_events_v1_research_searches__search_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/searches/{search_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Research Search Evidence */
        get: operations["list_research_search_evidence_v1_research_searches__search_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/uploads/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize Upload */
        post: operations["finalize_upload_v1_uploads_finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/uploads/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Presigned Upload */
        post: operations["create_presigned_upload_v1_uploads_presign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivatePolicyRequest */
        ActivatePolicyRequest: {
            /** Approved Evaluation Id */
            approved_evaluation_id: string;
            /** Reason */
            reason: string;
        };
        /** ActivatePromptRequest */
        ActivatePromptRequest: {
            /** Approved Evaluation Id */
            approved_evaluation_id: string;
            /** Reason */
            reason: string;
        };
        /** ActivationResponse */
        ActivationResponse: {
            /** Approved Evaluation Id */
            approved_evaluation_id: string;
            /** Resource Id */
            resource_id: string;
            /** Status */
            status: string;
        };
        /** AnswerCitationItem */
        AnswerCitationItem: {
            /** Chunk Id */
            chunk_id?: string | null;
            /** Citation Id */
            citation_id: string;
            /** Document Version Id */
            document_version_id?: string | null;
        };
        /** AnswerClaimItem */
        AnswerClaimItem: {
            /** Citation Ids */
            citation_ids: string[];
            /** Citations */
            citations?: components["schemas"]["AnswerCitationItem"][];
            /** Claim Text */
            claim_text: string;
            /** Ordinal */
            ordinal: number;
            /** Support Status */
            support_status: string;
        };
        /** AnswerVersionLinks */
        AnswerVersionLinks: {
            /** Governance */
            governance: string;
            /** Research Search */
            research_search: string;
            /** Review Queue */
            review_queue: string;
            /** Self */
            self: string;
        };
        /** CreateIndexBuildRequest */
        CreateIndexBuildRequest: {
            /** Policy Version */
            policy_version: string;
            /** Reason */
            reason: string;
            /** Source Ids */
            source_ids?: string[] | null;
            /** Use Case */
            use_case?: string | null;
        };
        /** CreateResearchSearchRequest */
        CreateResearchSearchRequest: {
            /** Comparator */
            comparator?: string | null;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /** Evidence Types */
            evidence_types?: components["schemas"]["StudyDesign"][];
            /**
             * Intended Use
             * @default literature_search
             */
            intended_use: string;
            /** Intervention */
            intervention?: string | null;
            /**
             * Only Approved Sources
             * @default true
             */
            only_approved_sources: boolean;
            /** Population */
            population?: string | null;
            /** Question */
            question: string;
            /** Source Ids */
            source_ids: string[];
        };
        /** DocumentChunkItem */
        DocumentChunkItem: {
            /** Citation Id */
            citation_id: string;
            /** Ordinal */
            ordinal: number;
            /** Page From */
            page_from: number | null;
            /** Page To */
            page_to: number | null;
            /** Section */
            section: string | null;
            /** Text */
            text: string;
            /** Token Count */
            token_count: number;
        };
        /** DocumentDetailResponse */
        DocumentDetailResponse: {
            /** Block Summary */
            block_summary?: {
                [key: string]: string;
            } | null;
            /** Created At */
            created_at: string;
            current_version: components["schemas"]["DocumentVersionSummary"] | null;
            /** Current Version Id */
            current_version_id: string | null;
            /** Document Id */
            document_id: string;
            /** External Id */
            external_id: string | null;
            /** Source Id */
            source_id: string;
            /** Status */
            status: string;
            /** Title */
            title: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** DocumentEventItem */
        DocumentEventItem: {
            /** Code */
            code: string | null;
            /** Created At */
            created_at: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Safe Message */
            safe_message: string | null;
            /** Sequence */
            sequence: number;
            /** Status */
            status: string;
        };
        /** DocumentEventListResponse */
        DocumentEventListResponse: {
            /** Items */
            items: components["schemas"]["DocumentEventItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** DocumentListResponse */
        DocumentListResponse: {
            /** Items */
            items: components["schemas"]["DocumentSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** DocumentSummary */
        DocumentSummary: {
            /** Created At */
            created_at: string;
            /** Document Id */
            document_id: string;
            /** External Id */
            external_id: string | null;
            /** Media Type */
            media_type: string | null;
            /** Source Id */
            source_id: string;
            /** Status */
            status: string;
            /** Title */
            title: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** DocumentVersionDetail */
        DocumentVersionDetail: {
            /** Chunks */
            chunks?: components["schemas"]["DocumentChunkItem"][];
            /** Created At */
            created_at: string;
            /** Filename */
            filename: string | null;
            /** Malware Status */
            malware_status: string | null;
            /** Media Type */
            media_type: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Page Count */
            page_count: number | null;
            /** Parser Name */
            parser_name: string | null;
            /** Parser Version */
            parser_version: string | null;
            /** Phi Status */
            phi_status: string | null;
            /** Sha256 */
            sha256: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Version */
            version: number;
            /** Version Id */
            version_id: string;
        };
        /** DocumentVersionListResponse */
        DocumentVersionListResponse: {
            /** Items */
            items: components["schemas"]["DocumentVersionSummary"][];
        };
        /** DocumentVersionSummary */
        DocumentVersionSummary: {
            /** Created At */
            created_at: string;
            /** Filename */
            filename: string | null;
            /** Malware Status */
            malware_status: string | null;
            /** Media Type */
            media_type: string | null;
            /** Page Count */
            page_count: number | null;
            /** Parser Name */
            parser_name: string | null;
            /** Parser Version */
            parser_version: string | null;
            /** Phi Status */
            phi_status: string | null;
            /** Sha256 */
            sha256: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Version */
            version: number;
            /** Version Id */
            version_id: string;
        };
        /** FinalizeUploadRequest */
        FinalizeUploadRequest: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
        };
        /** FinalizeUploadResponse */
        FinalizeUploadResponse: {
            /** Document Id */
            document_id: string;
            /** Idempotent */
            idempotent: boolean;
            /** Status */
            status: string;
            /** Version Id */
            version_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndexBuildCreatedResponse */
        IndexBuildCreatedResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Links */
            links: {
                [key: string]: string;
            };
            /**
             * Retrieval Index Id
             * Format: uuid
             */
            retrieval_index_id: string;
            /** Status */
            status: string;
        };
        /** IndexRecordListResponse */
        IndexRecordListResponse: {
            /** Items */
            items: components["schemas"]["IndexRecordSummary"][];
        };
        /** IndexRecordSummary */
        IndexRecordSummary: {
            /** Chunk Count */
            chunk_count: number;
            /** Created At */
            created_at: string;
            /** Document Count */
            document_count: number;
            /** Manifest Checksum */
            manifest_checksum: string;
            /**
             * Retrieval Index Id
             * Format: uuid
             */
            retrieval_index_id: string;
            /** Status */
            status: string;
            /** Use Case */
            use_case: string;
        };
        /** IngestionJobDetailResponse */
        IngestionJobDetailResponse: {
            /** Attempt */
            attempt: number;
            /** Created At */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Events */
            events: components["schemas"]["IngestionJobEventItem"][];
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Updated At */
            updated_at: string;
        };
        /** IngestionJobEventItem */
        IngestionJobEventItem: {
            /** Code */
            code: string | null;
            /** Created At */
            created_at: string;
            /** Safe Message */
            safe_message: string | null;
            /** Sequence */
            sequence: number;
            /** Status */
            status: string;
        };
        /** ModelGatewayOverviewResponse */
        ModelGatewayOverviewResponse: {
            /** Active Policy Version */
            active_policy_version?: number | null;
            /** Active Prompt Count */
            active_prompt_count: number;
            /** Evaluation Status */
            evaluation_status: string;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
        };
        /** ModelPolicyListResponse */
        ModelPolicyListResponse: {
            /** Items */
            items: components["schemas"]["ModelPolicySummary"][];
        };
        /** ModelPolicySummary */
        ModelPolicySummary: {
            /** Allowed Models */
            allowed_models: string[];
            /** Allowed Providers */
            allowed_providers: string[];
            /** Approved At */
            approved_at?: string | null;
            /** Approved By */
            approved_by?: string | null;
            /** Policy Id */
            policy_id: string;
            /** Sha256 */
            sha256: string;
            /** Status */
            status: string;
            /** Use Cases */
            use_cases: string[];
            /** Version Number */
            version_number: number;
        };
        /** PresignUploadRequest */
        PresignUploadRequest: {
            /** Contains Phi */
            contains_phi: boolean;
            /** External Id */
            external_id?: string | null;
            /** Filename */
            filename: string;
            /** Media Type */
            media_type: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Source Id */
            source_id: string;
        };
        /** PresignUploadResponse */
        PresignUploadResponse: {
            /** Document Id */
            document_id: string;
            /** Expires At */
            expires_at: string;
            /** Job Id */
            job_id: string;
            /** Object Key */
            object_key: string;
            /** Upload Fields */
            upload_fields: {
                [key: string]: string;
            };
            /** Upload Url */
            upload_url: string;
            /** Version Id */
            version_id: string;
        };
        /** PromptTemplateListResponse */
        PromptTemplateListResponse: {
            /** Items */
            items: components["schemas"]["PromptTemplateSummary"][];
        };
        /** PromptTemplateSummary */
        PromptTemplateSummary: {
            /** Approved At */
            approved_at?: string | null;
            /** Approved By */
            approved_by?: string | null;
            /** Evaluation Status */
            evaluation_status: string;
            /** Name */
            name: string;
            /** Sha256 */
            sha256: string;
            /** Status */
            status: string;
            /** Template Id */
            template_id: string;
            /** Use Case */
            use_case: string;
            /** Version */
            version: number;
        };
        /** ProviderHealthItem */
        ProviderHealthItem: {
            /** Checked At */
            checked_at: string;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Provider Id */
            provider_id: string;
            /** Safe Code */
            safe_code?: string | null;
            /** Status */
            status: string;
        };
        /** ReprocessDocumentRequest */
        ReprocessDocumentRequest: {
            /** Target Chunker Version */
            target_chunker_version: string;
            /** Target Parser Version */
            target_parser_version: string;
            /** Version Id */
            version_id?: string | null;
        };
        /** ReprocessDocumentResponse */
        ReprocessDocumentResponse: {
            /** Document Id */
            document_id: string;
            /** Idempotent */
            idempotent: boolean;
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Version Id */
            version_id: string;
        };
        /** ResearchAnswerResponse */
        ResearchAnswerResponse: {
            /** Answer Id */
            answer_id: string;
            /** Answer Summary */
            answer_summary: string;
            /** Claims */
            claims?: components["schemas"]["AnswerClaimItem"][];
            /** Contradictions */
            contradictions?: string[];
            /** Created At */
            created_at?: string | null;
            /** Evidence Context Sha256 */
            evidence_context_sha256: string;
            /** Index Manifest Checksum */
            index_manifest_checksum?: string | null;
            /** Limitations */
            limitations?: string[];
            links: components["schemas"]["AnswerVersionLinks"];
            /** Model Id */
            model_id: string;
            /** Model Provider Id */
            model_provider_id: string;
            /** Policy Version */
            policy_version: string;
            /** Prompt Version */
            prompt_version: string;
            /** Research Run Id */
            research_run_id: string;
            /** Retrieval Index Id */
            retrieval_index_id?: string | null;
            /** Retrieval Run Id */
            retrieval_run_id: string;
            /** Status */
            status: string;
            /** Uncertainty */
            uncertainty?: string | null;
            /** Version */
            version: number;
        };
        /** ResearchCancelResponse */
        ResearchCancelResponse: {
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Search Id */
            search_id: string;
            /** Status */
            status: string;
        };
        /** ResearchEventItem */
        ResearchEventItem: {
            /** Created At */
            created_at: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Event Type */
            event_type: string;
            /** Safe Message */
            safe_message: string;
            /** Sequence */
            sequence: number;
        };
        /** ResearchEventListResponse */
        ResearchEventListResponse: {
            /** Items */
            items: components["schemas"]["ResearchEventItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ResearchEvidenceExclusionSummary */
        ResearchEvidenceExclusionSummary: {
            /** Kinds */
            kinds: {
                [key: string]: number;
            };
            /** Total */
            total: number;
        };
        /** ResearchEvidenceItem */
        ResearchEvidenceItem: {
            /** Citation Id */
            citation_id: string;
            /** Document Id */
            document_id: string;
            /** Rank */
            rank: number;
            /**
             * Retrieval Index Id
             * Format: uuid
             */
            retrieval_index_id: string;
            /**
             * Retrieval Run Id
             * Format: uuid
             */
            retrieval_run_id: string;
            /** Score Source */
            score_source: string;
            /** Score Value */
            score_value: number;
        };
        /** ResearchEvidenceListResponse */
        ResearchEvidenceListResponse: {
            /** Abstention Reason */
            abstention_reason?: string | null;
            exclusions: components["schemas"]["ResearchEvidenceExclusionSummary"];
            /** Items */
            items: components["schemas"]["ResearchEvidenceItem"][];
        };
        /** ResearchSearchCreatedResponse */
        ResearchSearchCreatedResponse: {
            /** Job Id */
            job_id: string;
            links: components["schemas"]["ResearchSearchLinks"];
            /** Search Id */
            search_id: string;
            /** Status */
            status: string;
        };
        /** ResearchSearchDetail */
        ResearchSearchDetail: {
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Completed At */
            completed_at?: string | null;
            /** Created At */
            created_at: string;
            /** Current Step */
            current_step?: string | null;
            /** Intended Use */
            intended_use: string;
            /** Job Id */
            job_id?: string | null;
            links: components["schemas"]["ResearchSearchLinks"];
            /** Policy Version */
            policy_version: string;
            /** Question */
            question: string;
            /** Requested Sources */
            requested_sources: string[];
            /** Search Id */
            search_id: string;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
        };
        /** ResearchSearchLinks */
        ResearchSearchLinks: {
            /** Events */
            events: string;
            /** Job */
            job: string;
            /** Self */
            self: string;
        };
        /** ResearchSearchListResponse */
        ResearchSearchListResponse: {
            /** Items */
            items: components["schemas"]["ResearchSearchSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ResearchSearchSummary */
        ResearchSearchSummary: {
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Created At */
            created_at: string;
            /** Job Id */
            job_id?: string | null;
            /** Question */
            question: string;
            /** Search Id */
            search_id: string;
            /** Status */
            status: string;
        };
        /** RetentionRequest */
        RetentionRequest: {
            /** Reason */
            reason: string;
        };
        /** RetentionRequestResponse */
        RetentionRequestResponse: {
            /** Document Id */
            document_id: string;
            /** Status */
            status: string;
        };
        /**
         * StudyDesign
         * @enum {string}
         */
        StudyDesign: "randomized_controlled_trial" | "systematic_review" | "meta_analysis" | "cohort_study" | "case_control_study" | "case_series" | "case_report" | "guideline" | "preprint" | "unknown";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_provider_health_v1_admin_model_gateway_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderHealthItem"][];
                };
            };
        };
    };
    get_model_gateway_overview_v1_admin_model_gateway_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelGatewayOverviewResponse"];
                };
            };
        };
    };
    list_model_policies_v1_admin_model_gateway_policies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelPolicyListResponse"];
                };
            };
        };
    };
    activate_model_policy_v1_admin_model_gateway_policies__policy_id__activate_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivatePolicyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prompt_templates_v1_admin_model_gateway_prompts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptTemplateListResponse"];
                };
            };
        };
    };
    activate_prompt_template_v1_admin_model_gateway_prompts__template_id__activate_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivatePromptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_retrieval_indexes_v1_admin_retrieval_indexes_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexRecordListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_retrieval_index_v1_admin_retrieval_indexes_build_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIndexBuildRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexBuildCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_documents_v1_evidence_documents_get: {
        parameters: {
            query?: {
                source_id?: string | null;
                status?: string | null;
                media_type?: string | null;
                created_after?: string | null;
                created_before?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_document_v1_evidence_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_document_events_v1_evidence_documents__document_id__events_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentEventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_evidence_document_v1_evidence_documents__document_id__reprocess_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReprocessDocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReprocessDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_document_retention_v1_evidence_documents__document_id__retention_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetentionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetentionRequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_document_versions_v1_evidence_documents__document_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_document_version_v1_evidence_documents__document_id__versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_ingestion_job_v1_ingestion_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_research_searches_v1_research_searches_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchSearchListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_research_search_v1_research_searches_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResearchSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchSearchCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_research_search_v1_research_searches__search_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchSearchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_research_search_answer_v1_research_searches__search_id__answer_get: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: never;
            path: {
                search_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchAnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_research_search_v1_research_searches__search_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchCancelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_research_search_events_v1_research_searches__search_id__events_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                search_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchEventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_research_search_evidence_v1_research_searches__search_id__evidence_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                search_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchEvidenceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_upload_v1_uploads_finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinalizeUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalizeUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_presigned_upload_v1_uploads_presign_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | null;
                    };
                };
            };
        };
    };
}
