import unittest
from pathlib import Path


class ProductionRunbookDocsTests(unittest.TestCase):
    def test_operator_runbook_documents_required_commands_and_failure_triage(self):
        path = Path("docs/production/operator-runbook.md")
        text = path.read_text(encoding="utf-8")

        required_snippets = [
            "python scripts/run_phase_outputs.py --root . --output-dir outputs --source-registry config/source_registry.example.json --sqlite-db outputs/production.sqlite",
            "python scripts/inspect_production_store.py --sqlite-db outputs/production.sqlite --run-id local-phase-output-run --tenant-id local_tenant --workspace-id local_workspace",
            "python scripts/inspect_review_queue.py --sqlite-db outputs/production.sqlite --tenant-id local_tenant --workspace-id local_workspace --user-id reviewer-1 --role reviewer --status pending --run-id local-phase-output-run",
            "python scripts/record_review_decision.py --sqlite-db outputs/production.sqlite --review-id review-local-phase-output-run --tenant-id local_tenant --workspace-id local_workspace --user-id reviewer-1 --role reviewer --decision approve --comment \"Evidence reviewed for export.\" --decided-at 2026-06-15T00:05:00Z",
            "python scripts/export_report_from_store.py --sqlite-db outputs/production.sqlite --output-dir outputs --review-id review-local-phase-output-run --user-id reviewer-1 --role reviewer --report-type research_report --report-output outputs/exported/research_report.md --exported-at 2026-06-15T00:06:00Z",
            "python scripts/check_production_readiness.py --sqlite-db outputs/production.sqlite --artifact-manifest outputs/artifact_manifest.json --run-summary outputs/run_summary.json --run-id local-phase-output-run --tenant-id local_tenant --workspace-id local_workspace",
            "python scripts/summarize_production_observability.py --sqlite-db outputs/production.sqlite --run-id local-phase-output-run --tenant-id local_tenant --workspace-id local_workspace",
            "python scripts/run_incident_recovery_drill.py --sqlite-db outputs/production.sqlite --backup outputs/drill_production_backup.json --restored-sqlite-db outputs/drill_restored_production.sqlite --run-id local-phase-output-run --tenant-id local_tenant --workspace-id local_workspace",
            "python scripts/build_compliance_evidence_bundle.py --sqlite-db outputs/production.sqlite --artifact-manifest outputs/artifact_manifest.json --source-registry config/source_registry.example.json --backup outputs/production_backup.json --drill-json outputs/incident_recovery_drill.json --output outputs/compliance_evidence_bundle.json --run-id local-phase-output-run --tenant-id local_tenant --workspace-id local_workspace",
            "python scripts/record_compliance_attestation.py --bundle outputs/compliance_evidence_bundle.json --attestations outputs/compliance_attestations.jsonl --run-id local-phase-output-run --tenant-id local_tenant --workspace-id local_workspace --approver-id privacy-owner --approver-role privacy_owner --decision approve --comment \"Privacy evidence reviewed for pilot intake.\" --attested-at 2026-06-15T00:30:00Z",
            "python scripts/build_pilot_release_decision.py --bundle outputs/compliance_evidence_bundle.json --attestations outputs/compliance_attestations.jsonl --output outputs/pilot_release_decision.json --run-id local-phase-output-run --tenant-id local_tenant --workspace-id local_workspace --required-approver-role privacy_owner --required-approver-role security_owner --decided-at 2026-06-15T00:50:00Z",
            "python scripts/validate_deployment_config.py --env-file config/deployment.local.env",
            "python scripts/validate_deployment_package.py --manifest deploy/serverless/package.manifest.json",
            "python scripts/plan_deployment_package.py --manifest deploy/serverless/package.manifest.json --output outputs/deployment_package_inventory.json",
            "python scripts/build_deployment_archive.py --manifest deploy/serverless/package.manifest.json --archive outputs/vyu_deployment_package.zip --inventory outputs/deployment_package_inventory.json",
            "python scripts/write_deployment_package_evidence.py --manifest deploy/serverless/package.manifest.json --archive outputs/vyu_deployment_package.zip --inventory outputs/deployment_package_inventory.json --output outputs/deployment_package_evidence.json",
            "python scripts/check_deployment_release_package.py --manifest deploy/serverless/package.manifest.json --archive outputs/vyu_deployment_package.zip --inventory outputs/deployment_package_inventory.json --evidence outputs/deployment_package_evidence.json --output outputs/deployment_release_package_checklist.json",
            "python scripts/check_deployment_transcript_bundle.py --manifest deploy/serverless/package.manifest.json",
            "python scripts/build_deployment_release_evidence.py --package-evidence outputs/deployment_package_evidence.json --release-checklist outputs/deployment_release_package_checklist.json --transcript-bundle outputs/deployment_transcript_bundle.json --output outputs/deployment_release_evidence_summary.json",
            "python scripts/review_deployment_release_evidence.py --summary outputs/deployment_release_evidence_summary.json --decision approve --reviewer-id deployment-operator --reviewer-role deployment_operator --comment \"Deployment release evidence reviewed locally.\" --decided-at 2026-06-15T02:45:00Z --output outputs/deployment_release_review_decision.json",
            "python scripts/build_deployment_release_handoff.py --summary outputs/deployment_release_evidence_summary.json --review outputs/deployment_release_review_decision.json --created-at 2026-06-15T03:00:00Z --output outputs/deployment_release_handoff.json",
            "python scripts/build_deployment_release_handoff_archive.py --handoff outputs/deployment_release_handoff.json --created-at 2026-06-15T03:15:00Z --inventory outputs/deployment_release_handoff_inventory.json --archive outputs/deployment_release_handoff.zip",
            "python scripts/prepare_deployment_release_channel.py --inventory outputs/deployment_release_handoff_inventory.json --archive outputs/deployment_release_handoff.zip --created-at 2026-06-15T03:30:00Z --channel local-release-channel --output outputs/deployment_release_channel_preparation.json",
            "python scripts/accept_deployment_release_channel.py --preparation outputs/deployment_release_channel_preparation.json --decision approve --operator-id release-operator --operator-role deployment_operator --comment \"Release channel preparation accepted for local publication.\" --decided-at 2026-06-15T03:45:00Z --output outputs/deployment_release_channel_acceptance.json",
            "python scripts/prepare_deployment_release_channel_publication.py --acceptance outputs/deployment_release_channel_acceptance.json --publication-channel local-release-channel-publication --created-at 2026-06-15T04:00:00Z --output outputs/deployment_release_channel_publication_manifest.json",
            "python scripts/build_deployment_release_channel_evidence.py --publication outputs/deployment_release_channel_publication_manifest.json --index-name local-release-channel-evidence-index --created-at 2026-06-15T04:15:00Z --output outputs/deployment_release_channel_evidence_index.json",
            "python scripts/build_deployment_release_channel_export_summary.py --evidence-index outputs/deployment_release_channel_evidence_index.json --summary-name local-release-channel-evidence-export-summary --created-at 2026-06-15T04:30:00Z --output outputs/deployment_release_channel_export_summary.json",
            "python scripts/build_deployment_release_channel_target_readiness.py --export-summary outputs/deployment_release_channel_export_summary.json --readiness-name local-release-channel-target-readiness --created-at 2026-06-15T04:45:00Z --output outputs/deployment_release_channel_target_readiness.json",
            "python scripts/decide_deployment_release_channel_target.py --target-readiness outputs/deployment_release_channel_target_readiness.json --decision choose --target-family serverless_function --operator-id target-operator --operator-role deployment_operator --rationale \"Serverless function selected for provider planning.\" --decided-at 2026-06-15T05:00:00Z --output outputs/deployment_release_channel_target_decision.json",
            "python scripts/build_deployment_release_channel_provider_preflight.py --target-decision outputs/deployment_release_channel_target_decision.json --preflight-name local-release-channel-provider-planning-preflight --created-at 2026-06-15T05:30:00Z --output outputs/deployment_release_channel_provider_preflight.json",
            "python scripts/decide_deployment_release_channel_provider.py --provider-preflight outputs/deployment_release_channel_provider_preflight.json --decision proceed --planning-track serverless_provider_requirements_review --operator-id provider-operator --operator-role deployment_operator --rationale \"Provider planning approved from local preflight.\" --decided-at 2026-06-15T06:00:00Z --output outputs/deployment_release_channel_provider_decision.json",
            "outputs/deployment_transcript_bundle.json",
            "outputs/deployment_release_evidence_summary.json",
            "outputs/deployment_release_review_decision.json",
            "outputs/deployment_release_handoff.json",
            "outputs/deployment_release_handoff_inventory.json",
            "outputs/deployment_release_handoff.zip",
            "archive.sha256",
            "artifacts[].archive_entry",
            "artifacts[].hash_matches_expected",
            "handoff_status_ready",
            "release_evidence_paths_present",
            "recorded_hashes_match_files",
            "archive_entries_match_inventory",
            "archive_entry_hashes_match_inventory",
            "archive_metadata_deterministic",
            "outputs/deployment_release_channel_preparation.json",
            "inventory_sha256",
            "archive.expected_sha256",
            "archive.hash_matches_expected",
            "artifact_hashes.handoff_inventory_sha256",
            "artifact_hashes.handoff_archive_sha256",
            "inventory_status_ready",
            "inventory_checks_passed",
            "inventory_artifact_hashes_match",
            "archive_hash_matches_inventory",
            "next_actions[]",
            "outputs/deployment_release_channel_acceptance.json",
            "\"status\": \"accepted\"",
            "acceptance_id",
            "preparation.sha256",
            "preparation_status_ready",
            "preparation_checks_passed",
            "preparation_archive_hash_bound",
            "operator_metadata_present",
            "approve_requires_ready_preparation",
            "outputs/deployment_release_channel_publication_manifest.json",
            "acceptance.sha256",
            "acceptance.status",
            "acceptance_decision_approves",
            "acceptance_blocking_reasons_absent",
            "preparation_hash_present",
            "preparation_inventory_sha256_present",
            "publication_steps[]",
            "local_only_limits[]",
            "local_only_limits_recorded",
            "outputs/deployment_release_channel_evidence_index.json",
            "publication.sha256",
            "publication.status",
            "publication_checks_passed",
            "acceptance_sha256_present",
            "acceptance_status_accepted",
            "decision_approves",
            "preparation_sha256_present",
            "handoff_archive_hash_bound",
            "required_evidence_items_present",
            "evidence_items[].name",
            "evidence_items[].sha256",
            "summary.required_evidence_item_count",
            "summary.present_required_evidence_item_count",
            "outputs/deployment_release_channel_export_summary.json",
            "evidence_index.sha256",
            "evidence_index.status",
            "evidence_index_checks_passed",
            "publication_manifest_sha256_present",
            "acceptance_record_sha256_present",
            "preparation_manifest_sha256_present",
            "handoff_inventory_sha256_present",
            "release_evidence_summary_sha256_present",
            "release_review_decision_sha256_present",
            "package_evidence_sha256_present",
            "required_evidence_counts_complete",
            "evidence_hashes.evidence_index_sha256",
            "evidence_hashes.publication_manifest_sha256",
            "required_evidence_items[].name",
            "optional_evidence_items[].name",
            "review_checklist[]",
            "blocking_reasons",
            "summary.review_checklist_item_count",
            "outputs/deployment_release_channel_target_readiness.json",
            "export_summary.sha256",
            "export_summary.status",
            "export_summary_status_ready",
            "evidence_index_sha256_present",
            "evidence_index_sha256_matches_export_summary",
            "selected_target_provider_absent",
            "provider_configuration_empty",
            "candidate_target_families[]",
            "handoff_checklist[]",
            "target_selection_scope",
            "summary.handoff_checklist_item_count",
            "outputs/deployment_release_channel_target_decision.json",
            "target_readiness.sha256",
            "target_readiness.status",
            "decision.value",
            "decision.selected_target_family",
            "target_readiness_checks_passed",
            "target_readiness_blocking_reasons_absent",
            "target_family_candidates_present",
            "choose_requires_candidate_target_family",
            "block_or_defer_requires_no_selected_target_family",
            "target_selection_scope_local_only",
            "next_actions[]",
            "summary.next_action_count",
            "outputs/deployment_release_channel_provider_preflight.json",
            "target_decision.sha256",
            "target_decision.status",
            "planning_scope",
            "selected_target_family",
            "target_decision_status_selected",
            "target_decision_checks_passed",
            "target_decision_blocking_reasons_absent",
            "decision_value_choose",
            "selected_target_family_present",
            "selected_target_family_in_candidates",
            "planning_requirements[]",
            "summary.planning_requirement_count",
            "outputs/deployment_release_channel_provider_decision.json",
            "provider_preflight.sha256",
            "provider_preflight.status",
            "planning_decision_scope",
            "decision.provider_planning_track",
            "provider_preflight_status_ready",
            "provider_preflight_checks_passed",
            "provider_preflight_blocking_reasons_absent",
            "proceed_requires_provider_planning_track",
            "block_or_defer_requires_no_provider_planning_track",
            "planning_scope_preflight_only",
            "python scripts/backup_production_store.py export --sqlite-db outputs/production.sqlite --backup outputs/production_backup.json",
            "python scripts/backup_production_store.py restore --backup outputs/production_backup.json --sqlite-db outputs/restored_production.sqlite",
            "review_tasks",
            "review_tasks[].decision",
            "review_decision_recorded",
            "report_export_decision_recorded",
            "outputs/exported/research_report.md",
            "connector_health_records",
            "connector_validation_records",
            "evidence_object_records",
            "retrieval_index_records",
            "retrieval_run_records",
            "production_research_memory_records",
            "readiness_check_results",
            "attention_reasons",
            "report_export.allowed_count",
            "restored_scope_inspection.inspectable",
            "restore.counts_match_backup",
            "ready_for_pilot_review",
            "policy_documents",
            "source_approval",
            "compliance_attestations.jsonl",
            "bundle_sha256",
            "pilot_release_decision.json",
            "approved_for_pilot",
            "required_attestation_missing",
            "## Failure Triage",
            "schema_version_current",
            "migration_history_present",
            "approved_sources_present",
            "artifact_checksums_match_files",
            "connector_health_present",
            "connector_validation_present",
            "evidence_objects_present",
            "retrieval_index_current",
            "retrieval_run_present",
            "research_memory_present",
            "review_approval_present",
            "report_export_audit_present",
            "run_summary_consistent",
            "wrong_scope_rejected",
        ]

        for snippet in required_snippets:
            self.assertIn(snippet, text)


if __name__ == "__main__":
    unittest.main()
